### PR TITLE
add traefik_labels config to allow disable reading traefik_labels

### PR DESCRIPTION
**Pull request by harb88**
I don't want this to automatically pull the hostnames from Traefik so I've added a flag and config option to disable this function.

I wasn't able to test this though as I couldn't figure out how to build this locally yet.

### CODE REVIEW

**Comment by moonbuggy** [comment]
It's a reasonable thing to do, but I want to have a think about the implementation. Give me a day or two?

I've deliberately not woven Traefik-specific code too deeply through the script because I've always assumed I'll end up adding support for other frontends eventually, so I'm not sure I want a Traefik-specific `-T` parameter. I might prefer a `--read_labels_from=traefik,caddy,whatever` sort of approach,

At the same time, I should probably move what Traefik-specific code there is into its own class, so it's nominally more prepared to handle other frontends in other classes. The config parameter would then be a 'select which frontend class(es) to load' deal.

I'm not sure I'd want to set the default for Traefik to _false_ . It's definitely the sensible thing to do, but it would be a breaking change in my usage. Easily fixed, obviously, but I don't know if I should push a breaking change towards others without warning. (I really have no idea how many people use this thing and how they use it.) It may make more sense to default to _true_ for now, then change the default after some time to allow people to become aware of the setting.

As for building it yourself, `./build.sh` should do it, but you're actually the first person I'm aware of that's tried to build any of my images themselves, so I'm not surprised if I've missed something in my build system. :) I assume you're probably missing a requirement and the builder isn't sensibly indicating what.

I'd actually be very interested to see the output you're getting from `./build.sh`.

You could try `rm -rf .build_data; NO_QEMU=1 NO_BUILD=1 ./build.sh alpine-amd64`.  That will run everything except the `docker build` command, and simplify things by only preparing to build the standalone image for a native x64 architecture with fresh data from upstream sources. If that runs without error but it still fails when you enable the build command, you could try `NO_QEMU=1 NO_BUILD_MULTIARCH=1 ./build.sh alpine-amd64` to force it to build in an older (probably better supported) manner.

If it's just the `docker build` step that's failing, this would be relevant:
```
$ docker --version
Docker version 26.1.3, build b72abbb
$ docker buildx version
github.com/docker/buildx v0.14.0 171fcbe
```

If you want to build directly, you'll need to either remove a `COPY` command from the Dockerfile or create a file and folder it expects to see (although it will be slow for some other architectures because it will build some Python wheels from scratch without the build system importing pre-built wheels):
```
touch _dummyfile; mkdir -p .imports/amd64
docker build --progress=auto --load --rm \
        --platform=linux/amd64 --target=standalone \
        --file Dockerfile \
        --build-arg API_BACKEND=gunicorn \
        --build-arg BUILD_PYTHON_VERSION=3.11 \
        --build-arg FROM_IMAGE=moonbuggy2000/alpine-s6-python:3.11 \
        --tag moonbuggy2000/dnsmasq-updater:2.0.3-script-amd64 .
```

**Comment by harb88** [comment]
No worries, there's no rush on this, I only discovered this repo the other day when I started re-architecting my homelab and wanted a better way to work with my services locally than my current method which is IPs and ports.

The real reason I hadn't tested it yet was because I didn't want to run the build script directly on my server and I don't currently have a Linux dev environment setup and just haven't had time to get anything up.

I tried directly building the Dockerfile but of course I ran into the issues you mentioned above. Now that you've given me some clearer instructions I'll give it a go when I get some time later today.

I'm also happy to update the PR with the changes you mention. It does make way more sense to have it not be Traefik specific, so I'll see if I can clean it up a bit more and if I can get a working test build going I can be more confident in my changes as well.

I didn't really expect this PR to get merged immediately anyway, just thought it would be nicer to at least do some work myself instead of just raising an issue.

**Comment by moonbuggy** [comment]
There's actually far less Traefik-specific code in the thing than I remember. :) Four lines, give or take. So moving things into classes can wait until I'm actually adding more frontends and it's warranted.

Anyways, I have something I'll push probably within 24 hours. It's basically what you've suggested, but implemented via a list instead of a boolean, as I described above. And in a different _argparse_ group.

I decided a good compromise on the 'traafik_hostnames=_False_' by default deal was to default to _False_ in the script itself but add an `ENV` variable to enable it by default in the Dockerfile. For people using Docker frontends like Portainer, that `ENV` will be retained and they'll see it if they look, so hopefully it'll be less of a surprise for at least some people when I eventually disable it int he Dockerfile. :)

Yeah, that `COPY` command is annoying. I haven't had a good way of doing a `COPY_ONLY_IF_EXISTS` to get around that problem. Although I have recently been thinking about a workaround, just not gotten around to it yet.

If it helps, the build system should be mostly self-contained. It will make a few new folders and store some cached repo data, but they'll all be in the Git repo's path. It shouldn't directly touch any files outside of that path, although it will grab a few Docker images so it will write some data to wherever Docker stores you images. I _think_ everything would be removed by `rm -rf docker-dnsmasq-updater; docker image prune` or something very similar.

I know a stranger on the internet saying this doesn't really help, but I can assure you there's nothing malicious in my code. :) I can't vouch for all the images it might pull, but _I_ trust them enough to run them.

Obviously the sensible thing to do it not run it on a production server, but the build system shouldn't make a mess if you do.

And I do appreciate a PR with a solution attached. Certainly no complaints from me if someone wants to fix a problem they've found rather than just point at it. :) But I found myself more motivated than I anticipated and I have something coded here now that I've tested, so it's not necessary to do any more yourself. I mean, you're welcome to if you want, and maybe you'll come up with something I like more than what I've done. Just don't feel obliged.

I'm happy to add a "Contributors" section to the README, or add you manually as a contributor (if I'm able to - I dunno?)  if I don't end up merging your PR, if that's a concern..?

**Comment by moonbuggy** [comment]
Actually, I just pushed a couple of commits to the dev branch, so you can see [what I expect to end up with](https://github.com/moonbuggy/docker-dnsmasq-updater/commit/573fb837d641faa68b2df798ae7f7ed9aa9d510a), if you want.

I haven't finished testing it yet, I got distracted and made some improvements to the healthcheck mid-testing.  :) I'll test the last few things tomorrow and push after that.

edit: Obviously I need to finish updating _README.md_ too, but I'll finish testing functionality before I do that.

**Comment by moonbuggy** [comment]
I've tested the changes I implemented and they seem okay. The images are building now and will be pushed shortly.

Thanks for the suggestion and PR. :)

**Pull request closed without merging**
